run:
    concurrency: 8
    timeout: 2m
    issues-exit-code: 1
    tests: false

linters-settings:
    gocognit:
        min-complexity: 30
    gocyclo:
        min-complexity: 15
    gofmt:
        simplify: true
    gosimple:
        go: "1.19"
        checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    govet:
        check-shadowing: true
        enable-all: true
    nestif:
        min-complexity: 5
    staticcheck:
        go: "1.19"
        checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    stylecheck:
        go: "1.19"
        checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    thelper:
        test:
            first: true
            name: true
            begin: true
        benchmark:
            first: true
            name: true
            begin: true
        tb:
           first: true
           name: true
           begin: true
    unused:
        go: "1.19"

linters:
    disable-all: false
    enable-all: true
    disable:
        - cyclop
        # The following linters are disabled since they have been deprecated
        - forbidigo
        - deadcode
        - exhaustivestruct
        - structcheck
        - ifshort
        - scopelint
        - varcheck
        - maligned
        - golint
        - interfacer
        - rowserrcheck
        - sqlclosecheck
        - nosnakecase
        - wastedassign
    fast: false

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
    fix: true
    exclude:
        - "do not define dynamic errors, use wrapped static errors instead"
        - "variable name 'i' is too short for the scope of its usage"

